FROM ubuntu:20.04

ARG GITHUB_RUNNER_ALLOW_RUNASROOT
ARG GITHUB_REPOSITORY_URL
ARG GITHUB_RUNNER_TOKEN
ARG GITHUB_RUNNER_NAME
ARG GITHUB_RUNNER_LABELS
ARG GITHUB_RUNNER_VERSION
ARG GITHUB_RUNNER_CHECKSUMS

ENV DEBIAN_FRONTEND=noninteractive
ENV RUNNER_ALLOW_RUNASROOT=1
ENV PATH="/root/.local/bin:/root/.poetry/bin:/root/.profile:$PATH"

RUN apt update
RUN apt install -y --no-install-recommends apt-transport-https
RUN apt install -y --no-install-recommends ca-certificates
RUN apt install -y --no-install-recommends curl
RUN apt install -y --no-install-recommends gnupg2
RUN apt install -y --no-install-recommends software-properties-common
RUN apt install -y --no-install-recommends lsb-release
RUN apt install -y --no-install-recommends wget
RUN apt install -y --no-install-recommends git
RUN apt install -y --no-install-recommends python3
RUN apt install -y --no-install-recommends python3-pip
RUN apt install -y --no-install-recommends python3-setuptools
RUN apt install -y --no-install-recommends python3-venv

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"
RUN apt update && apt install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-compose-plugin
RUN docker compose

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN . ~/.nvm/nvm.sh && nvm install 20.12.0
RUN python3 -m pip install pipx

RUN apt clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/runner
WORKDIR /home/runner

RUN curl -o actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${GITHUB_RUNNER_VERSION}/actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz
RUN echo "${GITHUB_RUNNER_CHECKSUMS}  actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz" | shasum -a 256 -c

RUN tar xzf ./actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz

RUN ./bin/installdependencies.sh

RUN rm -f ./actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz

CMD ./config.sh --url $GITHUB_REPOSITORY_URL --token $GITHUB_RUNNER_TOKEN --name $GITHUB_RUNNER_NAME --labels $GITHUB_RUNNER_LABELS --ephemeral && ./run.sh
