FROM docker

ARG GITHUB_RUNNER_ALLOW_RUNASROOT
ARG GITHUB_REPOSITORY_URL
ARG GITHUB_RUNNER_TOKEN
ARG GITHUB_RUNNER_NAME
ARG GITHUB_RUNNER_LABELS
ARG GITHUB_RUNNER_VERSION
ARG GITHUB_RUNNER_CHECKSUMS

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
ENV RUNNER_ALLOW_RUNASROOT=1
ENV PATH="/root/.local/bin:/root/.poetry/bin:/root/.profile:$PATH"
ENV LD_LIBRARY_PATH /usr/local/lib:/usr/lib:/lib

RUN apk add --update --no-cache curl
RUN apk add --update --no-cache wget
RUN apk add --update --no-cache git
RUN apk add --update --no-cache perl-utils
RUN apk add --update --no-cache dotnet6-sdk
RUN apk add --update --no-cache gcompat
RUN apk add --update --no-cache iptables
RUN apk add --update --no-cache ip6tables
RUN apk add --update --no-cache bash

RUN mkdir -p /home/runner
WORKDIR /home/runner

RUN curl -o actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${GITHUB_RUNNER_VERSION}/actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz
RUN echo "${GITHUB_RUNNER_CHECKSUMS}  actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz" | shasum -a 256 -c

RUN tar xzf ./actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz

RUN rm -f ./actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz