name: Run tests nodejs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  node-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use, Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Linter
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test